spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/xzsd?serverTimezone=UTC
        username: root
        password: 82468246Ye.
        druid:
            initialSize: 1
            minIdle: 1
            maxActive: 20
            maxWait: 60000
            validationQuery: select 'x' from dual
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            filters: stat,slf4j
mybatis:
    mapper-locations: classpath:mybatis/mapper/**/*Mapper.xml
    config-location: classpath:mybatis/mybatis-config.xml